- repo: https://github.com/psf/black
  rev: stable
  hooks:
    - id: black
      language_version: python3
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v1.2.3
  hooks:
    - id: check-merge-conflict
    - id: debug-statements
    - id: detect-aws-credentials
    - id: check-added-large-files
    - id: detect-private-key
    - id: trailing-whitespace
    - id: flake8
      args: ['--ignore=E129,E2,W503,E731', '--max-line-length=250']
    - id: end-of-file-fixer
# - repo: https://github.com/asottile/reorder_python_imports
#   rev: v1.3.4
#   hooks:
#     - id: reorder-python-imports
#       language_version: python3
- repo: https://github.com/Lucas-C/pre-commit-hooks-bandit
  rev: v1.0.3
  hooks:
    - id: python-bandit-vulnerability-check
      args: [-l, --recursive, -x, tests, -ll]
      files: .py$
